### PR TITLE
Add Billy Jacobson

### PR DESCRIPTION
**Pull request by dwsupplee**
Adding Billy to Java

### CODE REVIEW

**Comment by sduskis** [comment]
Which repos should Billy be in?

**Comment by JustinBeckwith** [comment]
@billyjacobson are you working in a specific product area, or do you just want all the Java repos?

**Comment by billyjacobson** [comment]
@sduskis I just requested this so I could be marked a reviewer and get emails for the java samples in google-cloud-java. Not sure if I need others at the moment

**Comment by JustinBeckwith** [comment]
Cool! In that case, can you add yourself to the `yoshi-java` group in `users.json`?

**Comment by billyjacobson** [comment]
@JustinBeckwith I did. The diff just hides the groups

**Pull request merged**
